server:
  port: 8201

spring:
  application:
    name: spring-cloud-api-gateway-internal
  main:
    web-application-type: reactive
  cloud:
    gateway:
      httpclient:
        pool:
          type: FIXED
          maxConnections: 100
          acquireTimeout: 45
        wiretap: true
      routes:
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/authService/**
          filters:
            - StripPrefix=1

        - id: train-ticket-service
          uri: lb://train-ticket-service
          predicates:
            - Path=/trainTicketService/**
          filters:
            - StripPrefix=1

eureka:
  client:
    enabled: true
    serviceUrl:
      defaultZone: http://host.docker.internal:8200/eureka